# These are supported funding model platforms

github: WasathTheekshana
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
custom: ['https://buymeacoffee.com/wasath']
